spring:
  application:
    name: ludotheque
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LUDOTHEQUE
      auto-index-creation: true
      uri: mongodb+srv://vanessa:mdpplsMA@44@cluster0.bmhoh7m.mongodb.net/?appName=Cluster0
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
