spring:
  application:
    name: ludotheque
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LUDOTHEQUE
      auto-index-creation: true
      uri: mongodb://localhost:27017/LUDOTHEQUE
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
